package com.sati.model;
// Generated 17 oct. 2022 à 19:09:55 by Hibernate Tools 4.3.6.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * EntrerMateriel generated by hbm2java
 */
@Entity
@Table(name = "entrer_materiel", catalog = "bd_gestoinpatrimoine")
public class EntrerMateriel implements java.io.Serializable {

	private Integer idEntrer;
	private Materiels materiels;
	private Personne personne;
	private Date dateEntrer;
	private Set<SourceFinancement> sourceFinancements = new HashSet<SourceFinancement>(0);
	private Set<Fournisseur> fournisseurs = new HashSet<Fournisseur>(0);

	public EntrerMateriel() {
	}

	public EntrerMateriel(Materiels materiels, Personne personne, Date dateEntrer) {
		this.materiels = materiels;
		this.personne = personne;
		this.dateEntrer = dateEntrer;
	}

	public EntrerMateriel(Materiels materiels, Personne personne, Date dateEntrer,
			Set<SourceFinancement> sourceFinancements, Set<Fournisseur> fournisseurs) {
		this.materiels = materiels;
		this.personne = personne;
		this.dateEntrer = dateEntrer;
		this.sourceFinancements = sourceFinancements;
		this.fournisseurs = fournisseurs;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ID_ENTRER", unique = true, nullable = false)
	public Integer getIdEntrer() {
		return this.idEntrer;
	}

	public void setIdEntrer(Integer idEntrer) {
		this.idEntrer = idEntrer;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_MATERIEL", nullable = false)
	public Materiels getMateriels() {
		return this.materiels;
	}

	public void setMateriels(Materiels materiels) {
		this.materiels = materiels;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID", nullable = false)
	public Personne getPersonne() {
		return this.personne;
	}

	public void setPersonne(Personne personne) {
		this.personne = personne;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DATE_ENTRER", nullable = false, length = 19)
	public Date getDateEntrer() {
		return this.dateEntrer;
	}

	public void setDateEntrer(Date dateEntrer) {
		this.dateEntrer = dateEntrer;
	}

	@ManyToMany(fetch = FetchType.LAZY, mappedBy = "entrerMateriels")
	public Set<SourceFinancement> getSourceFinancements() {
		return this.sourceFinancements;
	}

	public void setSourceFinancements(Set<SourceFinancement> sourceFinancements) {
		this.sourceFinancements = sourceFinancements;
	}

	@ManyToMany(fetch = FetchType.LAZY, mappedBy = "entrerMateriels")
	public Set<Fournisseur> getFournisseurs() {
		return this.fournisseurs;
	}

	public void setFournisseurs(Set<Fournisseur> fournisseurs) {
		this.fournisseurs = fournisseurs;
	}

}
