package com.sati.model;
// Generated 7 nov. 2022 à 12:20:01 by Hibernate Tools 4.3.6.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * EtatDemande generated by hbm2java
 */
@Entity
@Table(name = "etat_demande", catalog = "bd_gestoinpatrimoine")
public class EtatDemande implements java.io.Serializable {

	private Integer e;
	private Personne personne;
	private String libelleEtatDemande;
	private Set<Demande> demandes = new HashSet<Demande>(0);

	public EtatDemande() {
	}

	public EtatDemande(Personne personne) {
		this.personne = personne;
	}

	public EtatDemande(Personne personne, String libelleEtatDemande, Set<Demande> demandes) {
		this.personne = personne;
		this.libelleEtatDemande = libelleEtatDemande;
		this.demandes = demandes;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "E", unique = true, nullable = false)
	public Integer getE() {
		return this.e;
	}

	public void setE(Integer e) {
		this.e = e;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID", nullable = false)
	public Personne getPersonne() {
		return this.personne;
	}

	public void setPersonne(Personne personne) {
		this.personne = personne;
	}

	@Column(name = "LIBELLE_ETAT_DEMANDE", length = 10)
	public String getLibelleEtatDemande() {
		return this.libelleEtatDemande;
	}

	public void setLibelleEtatDemande(String libelleEtatDemande) {
		this.libelleEtatDemande = libelleEtatDemande;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "etatDemande")
	public Set<Demande> getDemandes() {
		return this.demandes;
	}

	public void setDemandes(Set<Demande> demandes) {
		this.demandes = demandes;
	}

}
