package com.sati.model;
// Generated 7 nov. 2022 à 12:20:01 by Hibernate Tools 4.3.6.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Magasin generated by hbm2java
 */
@Entity
@Table(name = "magasin", catalog = "bd_gestoinpatrimoine")
public class Magasin implements java.io.Serializable {

	private Integer idMagasin;
	private String nomMagasin;
	private Set<Materiels> materielses = new HashSet<Materiels>(0);

	public Magasin() {
	}

	public Magasin(String nomMagasin) {
		this.nomMagasin = nomMagasin;
	}

	public Magasin(String nomMagasin, Set<Materiels> materielses) {
		this.nomMagasin = nomMagasin;
		this.materielses = materielses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ID_MAGASIN", unique = true, nullable = false)
	public Integer getIdMagasin() {
		return this.idMagasin;
	}

	public void setIdMagasin(Integer idMagasin) {
		this.idMagasin = idMagasin;
	}

	@Column(name = "NOM_MAGASIN", nullable = false, length = 65535)
	public String getNomMagasin() {
		return this.nomMagasin;
	}

	public void setNomMagasin(String nomMagasin) {
		this.nomMagasin = nomMagasin;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "magasin")
	public Set<Materiels> getMaterielses() {
		return this.materielses;
	}

	public void setMaterielses(Set<Materiels> materielses) {
		this.materielses = materielses;
	}

}
