package com.sati.model;
// Generated 17 oct. 2022 à 19:09:55 by Hibernate Tools 4.3.6.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Materiels generated by hbm2java
 */
@Entity
@Table(name = "materiels", catalog = "bd_gestoinpatrimoine")
public class Materiels implements java.io.Serializable {

	private Integer idMateriel;
	private Magasin magasin;
	private TypeMateriel typeMateriel;
	private String docReference;
	private String emplacement;
	private String utilisateur;
	private String codeMateriel;
	private Set<EntrerMateriel> entrerMateriels = new HashSet<EntrerMateriel>(0);
	private Set<Demande> demandes = new HashSet<Demande>(0);

	public Materiels() {
	}

	public Materiels(Magasin magasin, TypeMateriel typeMateriel, String docReference, String emplacement,
			String utilisateur, String codeMateriel) {
		this.magasin = magasin;
		this.typeMateriel = typeMateriel;
		this.docReference = docReference;
		this.emplacement = emplacement;
		this.utilisateur = utilisateur;
		this.codeMateriel = codeMateriel;
	}

	public Materiels(Magasin magasin, TypeMateriel typeMateriel, String docReference, String emplacement,
			String utilisateur, String codeMateriel, Set<EntrerMateriel> entrerMateriels, Set<Demande> demandes) {
		this.magasin = magasin;
		this.typeMateriel = typeMateriel;
		this.docReference = docReference;
		this.emplacement = emplacement;
		this.utilisateur = utilisateur;
		this.codeMateriel = codeMateriel;
		this.entrerMateriels = entrerMateriels;
		this.demandes = demandes;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ID_MATERIEL", unique = true, nullable = false)
	public Integer getIdMateriel() {
		return this.idMateriel;
	}

	public void setIdMateriel(Integer idMateriel) {
		this.idMateriel = idMateriel;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_MAGASIN", nullable = false)
	public Magasin getMagasin() {
		return this.magasin;
	}

	public void setMagasin(Magasin magasin) {
		this.magasin = magasin;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_TYPEMAT", nullable = false)
	public TypeMateriel getTypeMateriel() {
		return this.typeMateriel;
	}

	public void setTypeMateriel(TypeMateriel typeMateriel) {
		this.typeMateriel = typeMateriel;
	}

	@Column(name = "DOC_REFERENCE", nullable = false, length = 65535)
	public String getDocReference() {
		return this.docReference;
	}

	public void setDocReference(String docReference) {
		this.docReference = docReference;
	}

	@Column(name = "EMPLACEMENT", nullable = false, length = 65535)
	public String getEmplacement() {
		return this.emplacement;
	}

	public void setEmplacement(String emplacement) {
		this.emplacement = emplacement;
	}

	@Column(name = "UTILISATEUR", nullable = false, length = 65535)
	public String getUtilisateur() {
		return this.utilisateur;
	}

	public void setUtilisateur(String utilisateur) {
		this.utilisateur = utilisateur;
	}

	@Column(name = "CODE_MATERIEL", nullable = false, length = 65535)
	public String getCodeMateriel() {
		return this.codeMateriel;
	}

	public void setCodeMateriel(String codeMateriel) {
		this.codeMateriel = codeMateriel;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "materiels")
	public Set<EntrerMateriel> getEntrerMateriels() {
		return this.entrerMateriels;
	}

	public void setEntrerMateriels(Set<EntrerMateriel> entrerMateriels) {
		this.entrerMateriels = entrerMateriels;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "materiels")
	public Set<Demande> getDemandes() {
		return this.demandes;
	}

	public void setDemandes(Set<Demande> demandes) {
		this.demandes = demandes;
	}

}
