package com.sati.model;
// Generated 7 nov. 2022 à 12:20:01 by Hibernate Tools 4.3.6.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Materiels generated by hbm2java
 */
@Entity
@Table(name = "materiels", catalog = "bd_gestoinpatrimoine")
public class Materiels implements java.io.Serializable {

	private Integer idMateriel;
	private Magasin magasin;
	private TypeMateriel typeMateriel;
	private String reference;
	private String emplacement;
	private String utilisateur;
	private String libelle;
	private int qte;
	private Set<EntrerMateriel> entrerMateriels = new HashSet<EntrerMateriel>(0);
	private Set<Demande> demandes = new HashSet<Demande>(0);

	public Materiels() {
	}

	public Materiels(Magasin magasin, TypeMateriel typeMateriel, String reference, String emplacement,
			String utilisateur, String libelle, int qte) {
		this.magasin = magasin;
		this.typeMateriel = typeMateriel;
		this.reference = reference;
		this.emplacement = emplacement;
		this.utilisateur = utilisateur;
		this.libelle = libelle;
		this.qte = qte;
	}

	public Materiels(Magasin magasin, TypeMateriel typeMateriel, String reference, String emplacement,
			String utilisateur, String libelle, int qte, Set<EntrerMateriel> entrerMateriels, Set<Demande> demandes) {
		this.magasin = magasin;
		this.typeMateriel = typeMateriel;
		this.reference = reference;
		this.emplacement = emplacement;
		this.utilisateur = utilisateur;
		this.libelle = libelle;
		this.qte = qte;
		this.entrerMateriels = entrerMateriels;
		this.demandes = demandes;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ID_MATERIEL", unique = true, nullable = false)
	public Integer getIdMateriel() {
		return this.idMateriel;
	}

	public void setIdMateriel(Integer idMateriel) {
		this.idMateriel = idMateriel;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_MAGASIN", nullable = false)
	public Magasin getMagasin() {
		return this.magasin;
	}

	public void setMagasin(Magasin magasin) {
		this.magasin = magasin;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_TYPEMAT", nullable = false)
	public TypeMateriel getTypeMateriel() {
		return this.typeMateriel;
	}

	public void setTypeMateriel(TypeMateriel typeMateriel) {
		this.typeMateriel = typeMateriel;
	}

	@Column(name = "REFERENCE", nullable = false, length = 65535)
	public String getReference() {
		return this.reference;
	}

	public void setReference(String reference) {
		this.reference = reference;
	}

	@Column(name = "EMPLACEMENT", nullable = false, length = 65535)
	public String getEmplacement() {
		return this.emplacement;
	}

	public void setEmplacement(String emplacement) {
		this.emplacement = emplacement;
	}

	@Column(name = "UTILISATEUR", nullable = false, length = 65535)
	public String getUtilisateur() {
		return this.utilisateur;
	}

	public void setUtilisateur(String utilisateur) {
		this.utilisateur = utilisateur;
	}

	@Column(name = "LIBELLE", nullable = false, length = 65535)
	public String getLibelle() {
		return this.libelle;
	}

	public void setLibelle(String libelle) {
		this.libelle = libelle;
	}

	@Column(name = "QTE", nullable = false)
	public int getQte() {
		return this.qte;
	}

	public void setQte(int qte) {
		this.qte = qte;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "materiels")
	public Set<EntrerMateriel> getEntrerMateriels() {
		return this.entrerMateriels;
	}

	public void setEntrerMateriels(Set<EntrerMateriel> entrerMateriels) {
		this.entrerMateriels = entrerMateriels;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "materiels")
	public Set<Demande> getDemandes() {
		return this.demandes;
	}

	public void setDemandes(Set<Demande> demandes) {
		this.demandes = demandes;
	}

}
