package com.sati.model;
// Generated 7 nov. 2022 à 12:20:01 by Hibernate Tools 4.3.6.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.Table;

/**
 * Role generated by hbm2java
 */
@Entity
@Table(name = "role", catalog = "bd_gestoinpatrimoine")
public class Role implements java.io.Serializable {

	private Integer idRole;
	private String role;
	private Set<Users> userses = new HashSet<Users>(0);

	public Role() {
	}

	public Role(String role) {
		this.role = role;
	}

	public Role(String role, Set<Users> userses) {
		this.role = role;
		this.userses = userses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ID_ROLE", unique = true, nullable = false)
	public Integer getIdRole() {
		return this.idRole;
	}

	public void setIdRole(Integer idRole) {
		this.idRole = idRole;
	}

	@Column(name = "ROLE", nullable = false, length = 65535)
	public String getRole() {
		return this.role;
	}

	public void setRole(String role) {
		this.role = role;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "concerne", catalog = "bd_gestoinpatrimoine", joinColumns = {
			@JoinColumn(name = "ID_ROLE", nullable = false, updatable = false) }, inverseJoinColumns = {
					@JoinColumn(name = "ID_USERS", nullable = false, updatable = false) })
	public Set<Users> getUserses() {
		return this.userses;
	}

	public void setUserses(Set<Users> userses) {
		this.userses = userses;
	}

}
