package com.sati.model;
// Generated 7 nov. 2022 à 12:20:01 by Hibernate Tools 4.3.6.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * SortirMateriel generated by hbm2java
 */
@Entity
@Table(name = "sortir_materiel", catalog = "bd_gestoinpatrimoine")
public class SortirMateriel implements java.io.Serializable {

	private Integer idSortir;
	private Demande demande;
	private RetourMateriel retourMateriel;
	private Date dateSortir;
	private Date dateRetour;
	private Set<RetourMateriel> retourMateriels = new HashSet<RetourMateriel>(0);
	private Set<Demande> demandes = new HashSet<Demande>(0);

	public SortirMateriel() {
	}

	public SortirMateriel(Demande demande) {
		this.demande = demande;
	}

	public SortirMateriel(Demande demande, RetourMateriel retourMateriel, Date dateSortir, Date dateRetour,
			Set<RetourMateriel> retourMateriels, Set<Demande> demandes) {
		this.demande = demande;
		this.retourMateriel = retourMateriel;
		this.dateSortir = dateSortir;
		this.dateRetour = dateRetour;
		this.retourMateriels = retourMateriels;
		this.demandes = demandes;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ID_SORTIR", unique = true, nullable = false)
	public Integer getIdSortir() {
		return this.idSortir;
	}

	public void setIdSortir(Integer idSortir) {
		this.idSortir = idSortir;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_DEMANDE", nullable = false)
	public Demande getDemande() {
		return this.demande;
	}

	public void setDemande(Demande demande) {
		this.demande = demande;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_RETOURMATERIEL")
	public RetourMateriel getRetourMateriel() {
		return this.retourMateriel;
	}

	public void setRetourMateriel(RetourMateriel retourMateriel) {
		this.retourMateriel = retourMateriel;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DATE_SORTIR", length = 19)
	public Date getDateSortir() {
		return this.dateSortir;
	}

	public void setDateSortir(Date dateSortir) {
		this.dateSortir = dateSortir;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DATE_RETOUR", length = 19)
	public Date getDateRetour() {
		return this.dateRetour;
	}

	public void setDateRetour(Date dateRetour) {
		this.dateRetour = dateRetour;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "sortirMateriel")
	public Set<RetourMateriel> getRetourMateriels() {
		return this.retourMateriels;
	}

	public void setRetourMateriels(Set<RetourMateriel> retourMateriels) {
		this.retourMateriels = retourMateriels;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "sortirMateriel")
	public Set<Demande> getDemandes() {
		return this.demandes;
	}

	public void setDemandes(Set<Demande> demandes) {
		this.demandes = demandes;
	}

}
