package com.sati.model;
// Generated 17 oct. 2022 à 19:09:55 by Hibernate Tools 4.3.6.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TypeMateriel generated by hbm2java
 */
@Entity
@Table(name = "type_materiel", catalog = "bd_gestoinpatrimoine")
public class TypeMateriel implements java.io.Serializable {

	private Integer idTypemat;
	private String nomTypemat;
	private Set<Materiels> materielses = new HashSet<Materiels>(0);

	public TypeMateriel() {
	}

	public TypeMateriel(String nomTypemat) {
		this.nomTypemat = nomTypemat;
	}

	public TypeMateriel(String nomTypemat, Set<Materiels> materielses) {
		this.nomTypemat = nomTypemat;
		this.materielses = materielses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ID_TYPEMAT", unique = true, nullable = false)
	public Integer getIdTypemat() {
		return this.idTypemat;
	}

	public void setIdTypemat(Integer idTypemat) {
		this.idTypemat = idTypemat;
	}

	@Column(name = "NOM_TYPEMAT", nullable = false, length = 65535)
	public String getNomTypemat() {
		return this.nomTypemat;
	}

	public void setNomTypemat(String nomTypemat) {
		this.nomTypemat = nomTypemat;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "typeMateriel")
	public Set<Materiels> getMaterielses() {
		return this.materielses;
	}

	public void setMaterielses(Set<Materiels> materielses) {
		this.materielses = materielses;
	}

}
